# -*- coding: utf-8 -*-
"""sbertlr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkv1RLSTvYyS9iWjkRfF0RnP2nr40aSS
"""

import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    accuracy_score,
    f1_score,
    precision_score,
    recall_score
)

import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

train_df = pd.read_csv("/content/drive/MyDrive/train.csv")
test_df  = pd.read_csv("/content/drive/MyDrive/test.csv")

X_train = train_df["statement"].tolist()
y_train = train_df["label"].tolist()

X_test = test_df["statement"].tolist()
y_test = test_df["label"].tolist()

#  Load SBERT Model & Encode Sentences
!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

X_train_emb = model.encode(X_train, batch_size=32, show_progress_bar=True)
X_test_emb  = model.encode(X_test, batch_size=32, show_progress_bar=True)

sbert_lr = LogisticRegression(
    class_weight="balanced",
    max_iter=10000
)

sbert_lr.fit(X_train_emb, y_train)

y_pred = sbert_lr.predict(X_test_emb)

print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Depression", "Anxiety", "Stress"]
))

metrics = {
    "accuracy": accuracy_score(y_test, y_pred),
    "macro_f1": f1_score(y_test, y_pred, average="macro"),
    "weighted_f1": f1_score(y_test, y_pred, average="weighted"),
    "macro_precision": precision_score(y_test, y_pred, average="macro"),
    "macro_recall": recall_score(y_test, y_pred, average="macro")
}

metrics

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Normal", "Depression", "Anxiety", "Stress"]
)

disp.plot(cmap="Blues")
plt.title("SBERT + Logistic Regression")
plt.show()

report = classification_report(
    y_test,
    y_pred,
    target_names=["Normal", "Depression", "Anxiety", "Stress"],
    output_dict=True
)

f1_scores = [report[c]["f1-score"] for c in report if c in ["Normal", "Depression", "Anxiety", "Stress"]]

plt.bar(["Normal", "Depression", "Anxiety", "Stress"], f1_scores)
plt.ylabel("F1-score")
plt.title("Per-Class F1 — SBERT + LR")
plt.show()